
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "NUMBER accmanager country_name idaffmanager idapplication idbrowser idcampaign idoperator idpartner idverticaltype npwhere regioncontinent xresult : npwhere '(' x '[' idx ']' comparison value ',' node ',' node ')'node : resultnode : '(' leaf ')' leaf : NUMBER '.' digitsleaf : NUMBERdigits : digits digitdigits : digitdigit : NUMBERcomparison : '=' '='comparison : '<'comparison : '>'comparison : '<' '='value : digits '.' digitsvalue : digitsidx : idapplicationidx : idoperatoridx : idaffmanageridx : idbrowseridx : idpartneridx : idcampaignidx : idverticaltypeidx : regioncontinentidx : country_nameidx : accmanager"
    
_lr_action_items = {'npwhere':([0,28,37,],[2,2,2,]),'$end':([1,42,],[0,-1,]),'(':([2,28,37,],[3,31,31,]),'x':([3,],[4,]),'[':([4,],[5,]),'idapplication':([5,],[7,]),'idoperator':([5,],[8,]),'idaffmanager':([5,],[9,]),'idbrowser':([5,],[10,]),'idpartner':([5,],[11,]),'idcampaign':([5,],[12,]),'idverticaltype':([5,],[13,]),'regioncontinent':([5,],[14,]),'country_name':([5,],[15,]),'accmanager':([5,],[16,]),']':([6,7,8,9,10,11,12,13,14,15,16,],[17,-15,-16,-17,-18,-19,-20,-21,-22,-23,-24,]),'=':([17,19,20,],[19,26,27,]),'<':([17,],[20,]),'>':([17,],[21,]),'NUMBER':([18,20,21,23,24,25,26,27,29,30,31,34,39,41,],[25,-10,-11,25,-7,-8,-9,-12,25,-6,36,25,25,25,]),',':([22,23,24,25,30,32,33,34,38,42,],[28,-14,-7,-8,-6,37,-2,-13,-3,-1,]),'.':([23,24,25,30,36,],[29,-7,-8,-6,39,]),')':([24,25,30,33,35,36,38,40,41,42,],[-7,-8,-6,-2,38,-5,-3,42,-4,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'result':([0,28,37,],[1,33,33,]),'idx':([5,],[6,]),'comparison':([17,],[18,]),'value':([18,],[22,]),'digits':([18,29,39,],[23,34,41,]),'digit':([18,23,29,34,39,41,],[24,30,24,30,24,30,]),'node':([28,37,],[32,40,]),'leaf':([31,],[35,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> result","S'",1,None,None,None),
  ('result -> npwhere ( x [ idx ] comparison value , node , node )','result',13,'p_a','dt_new.py',41),
  ('node -> result','node',1,'p_b','dt_new.py',43),
  ('node -> ( leaf )','node',3,'p_c','dt_new.py',44),
  ('leaf -> NUMBER . digits','leaf',3,'p_d','dt_new.py',45),
  ('leaf -> NUMBER','leaf',1,'p_e','dt_new.py',46),
  ('digits -> digits digit','digits',2,'p_f','dt_new.py',47),
  ('digits -> digit','digits',1,'p_g','dt_new.py',48),
  ('digit -> NUMBER','digit',1,'p_h','dt_new.py',49),
  ('comparison -> = =','comparison',2,'p_i','dt_new.py',50),
  ('comparison -> <','comparison',1,'p_j','dt_new.py',51),
  ('comparison -> >','comparison',1,'p_k','dt_new.py',52),
  ('comparison -> < =','comparison',2,'p_l','dt_new.py',53),
  ('value -> digits . digits','value',3,'p_m','dt_new.py',54),
  ('value -> digits','value',1,'p_n','dt_new.py',55),
  ('idx -> idapplication','idx',1,'p_o','dt_new.py',56),
  ('idx -> idoperator','idx',1,'p_p','dt_new.py',57),
  ('idx -> idaffmanager','idx',1,'p_q','dt_new.py',58),
  ('idx -> idbrowser','idx',1,'p_r','dt_new.py',59),
  ('idx -> idpartner','idx',1,'p_s','dt_new.py',60),
  ('idx -> idcampaign','idx',1,'p_t','dt_new.py',61),
  ('idx -> idverticaltype','idx',1,'p_u','dt_new.py',62),
  ('idx -> regioncontinent','idx',1,'p_v','dt_new.py',63),
  ('idx -> country_name','idx',1,'p_w','dt_new.py',64),
  ('idx -> accmanager','idx',1,'p_x','dt_new.py',65),
]
