<result>        ::= np.where(x[<idx>] <comparison> (<value>), <node>, <node>)
<node>          ::= <result> |  <leaf>
<leaf>          ::= "'none'" | "'verylow'" | "'low'" | "'medium'" | "'high'"
<digits>        ::= <digits><digit> | <digit>
<digit>         ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
<comparison>    ::= "==" | "<" | ">" | "<="
<idx>           ::= "'idapplication'" | "'idoperator'" | "'idaffmanager'" | 
                "'idbrowser'" | "'city'" | "'idpartner'" | "'idcampaign'" | 
                "'idverticaltype'" | "'regioncontinent'" | "'country_name'" | 
                "'accmanager'"
<value>         ::= <digits>.<digits> | <digits>
