
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "NUMBER accmanager country_name high idaffmanager idapplication idbrowser idcampaign idoperator idpartner idverticaltype low medium none npwhere regioncontinent verylow xresult : npwhere '(' x '[' idx ']' comparison '(' value ')' ',' node ',' node ')'node : resultnode : leaf leaf : noneleaf : verylowleaf : lowleaf : mediumleaf : highdigits : digits digitdigits : digitdigit : NUMBERcomparison : '=' '='comparison : '<'comparison : '>'comparison : '<' '='idx : idapplicationidx : idoperatoridx : idaffmanageridx : idbrowseridx : idpartneridx : idcampaignidx : idverticaltypeidx : regioncontinentidx : country_nameidx : accmanagervalue : digits '.' digitsvalue : digits"
    
_lr_action_items = {'npwhere':([0,32,42,],[2,2,2,]),'$end':([1,44,],[0,-1,]),'(':([2,18,20,21,23,24,],[3,22,-13,-14,-12,-15,]),'x':([3,],[4,]),'[':([4,],[5,]),'idapplication':([5,],[7,]),'idoperator':([5,],[8,]),'idaffmanager':([5,],[9,]),'idbrowser':([5,],[10,]),'idpartner':([5,],[11,]),'idcampaign':([5,],[12,]),'idverticaltype':([5,],[13,]),'regioncontinent':([5,],[14,]),'country_name':([5,],[15,]),'accmanager':([5,],[16,]),']':([6,7,8,9,10,11,12,13,14,15,16,],[17,-16,-17,-18,-19,-20,-21,-22,-23,-24,-25,]),'=':([17,19,20,],[19,23,24,]),'<':([17,],[20,]),'>':([17,],[21,]),'NUMBER':([22,26,27,28,30,31,33,],[28,28,-10,-11,28,-9,28,]),')':([25,26,27,28,31,33,35,36,37,38,39,40,41,43,44,],[29,-27,-10,-11,-9,-26,-2,-3,-4,-5,-6,-7,-8,44,-1,]),'.':([26,27,28,31,],[30,-10,-11,-9,]),',':([29,34,35,36,37,38,39,40,41,44,],[32,42,-2,-3,-4,-5,-6,-7,-8,-1,]),'none':([32,42,],[37,37,]),'verylow':([32,42,],[38,38,]),'low':([32,42,],[39,39,]),'medium':([32,42,],[40,40,]),'high':([32,42,],[41,41,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'result':([0,32,42,],[1,35,35,]),'idx':([5,],[6,]),'comparison':([17,],[18,]),'value':([22,],[25,]),'digits':([22,30,],[26,33,]),'digit':([22,26,30,33,],[27,31,27,31,]),'node':([32,42,],[34,43,]),'leaf':([32,42,],[36,36,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> result","S'",1,None,None,None),
  ('result -> npwhere ( x [ idx ] comparison ( value ) , node , node )','result',15,'p_a','dt_new.py',70),
  ('node -> result','node',1,'p_b','dt_new.py',72),
  ('node -> leaf','node',1,'p_c','dt_new.py',73),
  ('leaf -> none','leaf',1,'p_d','dt_new.py',74),
  ('leaf -> verylow','leaf',1,'p_e','dt_new.py',75),
  ('leaf -> low','leaf',1,'p_f','dt_new.py',76),
  ('leaf -> medium','leaf',1,'p_g','dt_new.py',77),
  ('leaf -> high','leaf',1,'p_h','dt_new.py',78),
  ('digits -> digits digit','digits',2,'p_i','dt_new.py',79),
  ('digits -> digit','digits',1,'p_j','dt_new.py',80),
  ('digit -> NUMBER','digit',1,'p_k','dt_new.py',81),
  ('comparison -> = =','comparison',2,'p_l','dt_new.py',82),
  ('comparison -> <','comparison',1,'p_m','dt_new.py',83),
  ('comparison -> >','comparison',1,'p_n','dt_new.py',84),
  ('comparison -> < =','comparison',2,'p_o','dt_new.py',85),
  ('idx -> idapplication','idx',1,'p_p','dt_new.py',86),
  ('idx -> idoperator','idx',1,'p_q','dt_new.py',87),
  ('idx -> idaffmanager','idx',1,'p_r','dt_new.py',88),
  ('idx -> idbrowser','idx',1,'p_s','dt_new.py',89),
  ('idx -> idpartner','idx',1,'p_u','dt_new.py',90),
  ('idx -> idcampaign','idx',1,'p_v','dt_new.py',91),
  ('idx -> idverticaltype','idx',1,'p_w','dt_new.py',92),
  ('idx -> regioncontinent','idx',1,'p_x','dt_new.py',93),
  ('idx -> country_name','idx',1,'p_y','dt_new.py',94),
  ('idx -> accmanager','idx',1,'p_z','dt_new.py',95),
  ('value -> digits . digits','value',3,'p_aa','dt_new.py',96),
  ('value -> digits','value',1,'p_ab','dt_new.py',97),
]
