
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "NUMBER accmanager city country_name high idaffmanager idapplication idbrowser idcampaign idoperator idpartner idverticaltype low medium none npwhere regioncontinent verylow xresult : npwhere '(' x '[' idx ']' comparison '(' value ')' ',' node ',' node ')'node : resultnode : leaf leaf : noneleaf : verylowleaf : lowleaf : mediumleaf : highdigits : digits digitdigits : digitdigit : NUMBERcomparison : '=' '='comparison : '<'comparison : '>'comparison : '<' '='idx : idapplicationidx : idoperatoridx : idaffmanageridx : idbrowseridx : cityidx : idpartneridx : idcampaignidx : idverticaltypeidx : regioncontinentidx : country_nameidx : accmanagervalue : digits '.' digitsvalue : digits"
    
_lr_action_items = {'npwhere':([0,33,43,],[2,2,2,]),'$end':([1,45,],[0,-1,]),'(':([2,19,21,22,24,25,],[3,23,-13,-14,-12,-15,]),'x':([3,],[4,]),'[':([4,],[5,]),'idapplication':([5,],[7,]),'idoperator':([5,],[8,]),'idaffmanager':([5,],[9,]),'idbrowser':([5,],[10,]),'city':([5,],[11,]),'idpartner':([5,],[12,]),'idcampaign':([5,],[13,]),'idverticaltype':([5,],[14,]),'regioncontinent':([5,],[15,]),'country_name':([5,],[16,]),'accmanager':([5,],[17,]),']':([6,7,8,9,10,11,12,13,14,15,16,17,],[18,-16,-17,-18,-19,-20,-21,-22,-23,-24,-25,-26,]),'=':([18,20,21,],[20,24,25,]),'<':([18,],[21,]),'>':([18,],[22,]),'NUMBER':([23,27,28,29,31,32,34,],[29,29,-10,-11,29,-9,29,]),')':([26,27,28,29,32,34,36,37,38,39,40,41,42,44,45,],[30,-28,-10,-11,-9,-27,-2,-3,-4,-5,-6,-7,-8,45,-1,]),'.':([27,28,29,32,],[31,-10,-11,-9,]),',':([30,35,36,37,38,39,40,41,42,45,],[33,43,-2,-3,-4,-5,-6,-7,-8,-1,]),'none':([33,43,],[38,38,]),'verylow':([33,43,],[39,39,]),'low':([33,43,],[40,40,]),'medium':([33,43,],[41,41,]),'high':([33,43,],[42,42,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'result':([0,33,43,],[1,36,36,]),'idx':([5,],[6,]),'comparison':([18,],[19,]),'value':([23,],[26,]),'digits':([23,31,],[27,34,]),'digit':([23,27,31,34,],[28,32,28,32,]),'node':([33,43,],[35,44,]),'leaf':([33,43,],[37,37,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> result","S'",1,None,None,None),
  ('result -> npwhere ( x [ idx ] comparison ( value ) , node , node )','result',15,'p_a','dt_old.py',71),
  ('node -> result','node',1,'p_b','dt_old.py',73),
  ('node -> leaf','node',1,'p_c','dt_old.py',74),
  ('leaf -> none','leaf',1,'p_d','dt_old.py',75),
  ('leaf -> verylow','leaf',1,'p_e','dt_old.py',76),
  ('leaf -> low','leaf',1,'p_f','dt_old.py',77),
  ('leaf -> medium','leaf',1,'p_g','dt_old.py',78),
  ('leaf -> high','leaf',1,'p_h','dt_old.py',79),
  ('digits -> digits digit','digits',2,'p_i','dt_old.py',80),
  ('digits -> digit','digits',1,'p_j','dt_old.py',81),
  ('digit -> NUMBER','digit',1,'p_k','dt_old.py',82),
  ('comparison -> = =','comparison',2,'p_l','dt_old.py',83),
  ('comparison -> <','comparison',1,'p_m','dt_old.py',84),
  ('comparison -> >','comparison',1,'p_n','dt_old.py',85),
  ('comparison -> < =','comparison',2,'p_o','dt_old.py',86),
  ('idx -> idapplication','idx',1,'p_p','dt_old.py',87),
  ('idx -> idoperator','idx',1,'p_q','dt_old.py',88),
  ('idx -> idaffmanager','idx',1,'p_r','dt_old.py',89),
  ('idx -> idbrowser','idx',1,'p_s','dt_old.py',90),
  ('idx -> city','idx',1,'p_t','dt_old.py',91),
  ('idx -> idpartner','idx',1,'p_u','dt_old.py',92),
  ('idx -> idcampaign','idx',1,'p_v','dt_old.py',93),
  ('idx -> idverticaltype','idx',1,'p_w','dt_old.py',94),
  ('idx -> regioncontinent','idx',1,'p_x','dt_old.py',95),
  ('idx -> country_name','idx',1,'p_y','dt_old.py',96),
  ('idx -> accmanager','idx',1,'p_z','dt_old.py',97),
  ('value -> digits . digits','value',3,'p_aa','dt_old.py',98),
  ('value -> digits','value',1,'p_ab','dt_old.py',99),
]
